# Generated by Django 6.0.5 on 2026-05-30 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheinoifpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código da categoria')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da categoria')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código do local')),
                ('predio', models.CharField(max_length=5, verbose_name='Prédio')),
                ('andar', models.CharField(max_length=5, verbose_name='Andar')),
                ('nome', models.CharField(default='Sala do IFPI', max_length=25, verbose_name='Nome do local')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone do local')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do local')),
                ('sala_de_aula', models.BooleanField(default=False, verbose_name='Sala de aula?')),
                ('laboratorio', models.BooleanField(default=False, verbose_name='Laboratório?')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='criado_em',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Usuário'), (2, 'Servidor')], verbose_name='Tipo de Usuário'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acheinoifpi.local', verbose_name='Local de cadastro'),
        ),
    ]
