# Generated by Django 6.0.5 on 2026-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheinoifpi', '0002_categoria_local_usuario_ativo_usuario_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Usuário'), (2, 'Servidor')], null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
