# Generated by Django 6.0.5 on 2026-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheinoifpi', '0003_alter_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('cor', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarelo'), ('danger', 'Vermelho'), ('info', 'Azul claro'), ('secondary', 'Cinza')], default='primary', max_length=20, verbose_name='Cor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
