# Generated by Django 6.0.5 on 2026-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheinoifpi', '0004_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_alterada',
            field=models.BooleanField(default=False, verbose_name='Senha alterada?'),
        ),
        migrations.AlterField(
            model_name='local',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do local'),
        ),
    ]
