# Generated by Django 6.0.5 on 2026-06-05 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheinoifpi', '0006_usuario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, unique=True, verbose_name='UUID')),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho do item')),
                ('cor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor do item')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Material do item')),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código do item')),
                ('marca_ou_modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca ou modelo do item')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do item')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de devolução')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='itens/fotos/', verbose_name='Foto do item')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do item')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.IntegerField(choices=[(1, 'Perdido'), (2, 'Encontrado'), (3, 'Devolvido'), (4, 'Outro')], default=1, verbose_name='Status')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acheinoifpi.categoria', verbose_name='Categoria')),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_recuperados', to=settings.AUTH_USER_MODEL, verbose_name='Dono do item')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acheinoifpi.local', verbose_name='Local que foi encontrado')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_registro', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
